name = "loadbalancer"
main = "src/index.js"

compatibility_date = "2022-11-29"

[vars]
# Specify all origins that you want to monitor.
ORIGINS = [
	"https://dev.passky.org",
	"https://dev2.passky.org"
]
# To monitor specific endpoint.
ENDPOINT = "/?action=getInfo"

[[kv_namespaces]]
binding = "KV"
id = "7ff95bed4f6d407890ddafa99122bbfb"

[triggers]
crons = ["* * * * *"]