name = "passky-loadbalancer-eu"
main = "src/index.js"

compatibility_date = "2022-12-06"

[vars]

# Specify all origins that you want to monitor.
ORIGINS = [
	"https://eu3.passky.org",
	"https://eu4.passky.org"
]

# Used if you choose Weighted round robin algorithm
WEIGHTS = [
	50,
	50
]

# To monitor specific endpoint.
ENDPOINT = "/?action=getInfo"

# Choose Load Balancing algorithm
# 	Static:
#			- 0 (Round robin)
#			- 1 (Weighted round robin)
BALANCING_ALGO = 0

[[kv_namespaces]]
binding = "KV"
id = "1c92215efde74e198906be9e3d2a3162"